---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  # namespace: elasticsearch
  labels:
    component: elasticsearch
    role: coordinator
spec:
  selector:
    component: elasticsearch
    role: coordinator
  ports:
  - name: http
    port: 9200
