apiVersion: "storageos.com/v1"
kind: StorageOSCluster
metadata:
  name: "storageos"
spec:
  secretRefName: "storageos-api" # Reference from the Secret created in the previous step
  secretRefNamespace: "default"  # Namespace of the Secret
  k8sDistro: "openshift"
  nodeSelectorTerms:
    - matchExpressions:
      - key: "node-role.kubernetes.io/compute" # Select non master nodes
        operator: In
        values:
        - "true"
